### PR TITLE
update composer.json to support php7.3 and 8.x

### PR DESCRIPTION
**Pull request by ibnuhalimm**
Minimum requirement of laravel 8 is php 7.3 or 8.0

### CODE REVIEW

**Comment by kevariable** [comment]
Please accept this pull request

**Comment by alanyeong** [comment]
> Minimum requirement of laravel 8 is php 7.3 or 8.0
> Please accept this pull request

Alright, accepted the pull request.

**Comment by alanyeong** [comment]
@ibnuhalimm Thanks for letting me know, I have updated the composer.json to support ^PHP 7.3 & ^PHP 8, as well as Laravel 7 / 8 / 9. I have also added credits section to credit you :)

**Comment by ibnuhalimm** [comment]
Oh yes, nvm
I dont know that laravel 9 requires php 8.x

Thank you

**Pull request merged**
